check-dependencies:
  stage: lint
  before_script:
  # Installing these dependencies during the job because the job runs very infrequently and at night.
  # If these were to be moved to a Dockerfile, it would slow down the pipeline substantially.
  # This can be done once it is moved to its own repo.
    - apt update
    - apt install -y curl
    - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  script:
    - poetry install
    - poetry run check_dependencies
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
      allow_failure: false
    - when: manual
      allow_failure: true
  